### ISSUE TITLE
Access modifier is incorrect for Single emitter

### ISSUE THREAD

**Issue by noheltcj** [noheltcj/RxCommon#15]
Currently, the emitter is public for Single. This should not be directly accessible.

**Comment by Hiosdra** [comment]
Do you mean to add:
`@Deprecated("Only intended for internal use.", level = DeprecationLevel.HIDDEN)`
to `next(value E)`?

**Comment by noheltcj** [comment]
@Hiosdra that part is necessary for initializing the Single using the create with emitter constructor.

The issue is on line 12 of Single.kt

With that field left public, it's accessible like so: 
```
val single = Single(just = 1)
single.emitter.next(2)
```
Which is undesirable for multiple reasons :)
