### ISSUE TITLE
Sources need a doOnNext method and operator

### ISSUE THREAD

**Issue by noheltcj** [noheltcj/RxCommon#16]
While it's possible to work around not having this. Semantically, the workaround does not fit.

**Comment by Hiosdra** [comment]
I'll do this ;)

**Comment by Hiosdra** [comment]
PR: https://github.com/noheltcj/RxCommon/pull/17

**Comment by noheltcj** [comment]
Thanks! I will check this out tonight.

**Comment by noheltcj** [comment]
resolved by #17 

Thanks @Hiosdra 

(Also, next time I'll remember to reference the issue from the pull request when merging)
